resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  cluster: https://api.ci.openshift.org
  name: "4.5"
  namespace: ocp
tests:
- as: cvp-common-aws
  cron: '@yearly'
  steps:
    cluster_profile: aws
    workflow: optional-operators-cvp-common-aws
zz_generated_metadata:
  branch: cvp-ocp-4.5
  org: redhat-operator-ecosystem
  repo: playground
