base_images:
  base:
    cluster: https://api.ci.openshift.org
    name: ubi
    namespace: ocp
    tag: "7"

build_root:
  image_stream_tag:
    cluster: https://api.ci.openshift.org
    name: release
    namespace: openshift
    tag: golang-1.13

images:
- dockerfile_path: Dockerfile
  from: bin
  inputs:
    bin:
      as:
        - builder
    base:
      as:
        - runtime
  to: redhat-operator-ecosystem-playground

binary_build_commands: make build

promotion:
  namespace: ci
  tag: latest

tag_specification:
  cluster: https://api.ci.openshift.org
  namespace: ocp
  name: "4.4"

resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi

tests:
- as: unit
  commands: make test-unit
  container:
    from: src
- as: perf
  commands: make test-perf
  container:
    from: src
- as: e2e
  commands: make test-e2e
  openshift_installer_src:
    cluster_profile: aws
- as: e2e-periodic
  cron: '@yearly'
  commands: make test-e2e
  openshift_installer_src:
    cluster_profile: aws
